VR_NAME="Meta Quest 3"
VR_DETECT_USB=""
VR_DETECT_MANUAL=true
VR_DISPLAY_CONNECTOR=""
VR_WIDTH=2064
VR_HEIGHT=2208
VR_REFRESH=90
VR_SCALE=1
VR_OPENXR_RUNTIME="wivrn"
VR_BOOT_INIT=""
VR_WATCH_SERVICE="wivrn-watch"
