VR_NAME="Xreal Air Gen 1"
VR_DETECT_USB="3318:0424"
VR_DISPLAY_CONNECTOR="DP-1"
VR_WIDTH=1920
VR_HEIGHT=1080
VR_REFRESH=60
VR_SCALE=1
VR_OPENXR_RUNTIME="monado"
VR_BOOT_INIT="/usr/lib/vr-headset-init/xreal-init.sh"
VR_AUTO_START=false
